title: Maple Huang - Hair Dresser
description: Master's qualified hairdresser with 9+ years of experience specialising in contemporary, fashion-forward cuts, perms and colour
author: Maple Huang
url: https://maple-hairlab.github.io
baseurl: ""

# Jekyll settings
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Custom settings
show_excerpts: true

# Hide header links
header_pages: []
